comments, function to get sequence record

diff --git a/src/macros b/src/macros
--- a/src/macros
+++ b/src/macros
@@ -37,3 +37,23 @@ M_GET_TABLE='
     eval $LOGGER ERROR;
     return 1;
   fi'
+
+M_GET_FUNCTION='
+  declare -A FS;
+  declare -A FUNCTION_RECORD;
+  FS[function]="$P_FUNCTION";
+  if ! function_get_struct_by_name FS FUNCTION_RECORD; then
+    LOGGER_MSG="Function "$P_FUNCTION" not found";
+    eval $LOGGER ERROR;
+    return 1;
+  fi'
+
+M_GET_SEQUENCE='
+  declare -A SS;
+  declare -A SEQUENCE_RECORD;
+  SS[sequence]="$P_SEQUENCE";
+  if ! sequence_get_struct_by_name SS SEQUENCE_RECORD; then
+    LOGGER_MSG="Sequence "$P_SEQUENCE" not found";
+    eval $LOGGER ERROR;
+    return 1;
+  fi'
diff --git a/src/storage/tuple b/src/storage/tuple
--- a/src/storage/tuple
+++ b/src/storage/tuple
@@ -17,3 +17,27 @@ FUNCTION
 tuple_get_tuple_field1() {
 	:
 }
+
+: <<'FUNCTION'
+Description: Mark the tuple as not alive
+Parameters:
+ $1 - Table ID
+ $2 - pos
+FUNCTION
+tuple_set_notalive() {
+  local _TABLEID=$1
+	local _TUPLEPOS=$2
+	local _POS=0
+	let _POS=${_TUPLEPOS}+1
+
+  declare -A CH_DATA
+	CH_DATA[table]=${_TABLEID}
+	CH_DATA[pos]=${_POS}
+	CH_DATA[data]="0" # Marking not alive
+	if ! table_change_data CH_DATA; then
+		eval $LOGGER ERROR "Fail to change data on table"
+		declare -p CH_DATA
+		return 1
+	fi
+	return 0
+}
